### Get All Products
GET http://localhost:3001/api/products
Accept: application/json

### Create a New Product
POST http://localhost:3001/api/products
Content-Type: application/json

{
  "name": "Title Supreme Watch",
  "description": "This sleek and modern smartwatch comes with a variety of features including fitness tracking, notifications, and customizable watch faces.",
  "price": 299,
  "category": "66a29074724ae190c00fdaef",  
  "stock": 20,
  "imageUrl": "uploads/SmartWatch.png",
}

### Get Product by ID
GET http://localhost:3001/api/products/66aa8b2df19b88f379906931
Accept: application/json

### Update a Product
PUT http://localhost:3001/api/products/66aae76d1a549eec63bce240
Content-Type: application/json
{
  "name": "Titan Supreme Watch",
}

### Delete a Product
DELETE http://localhost:3001/api/products/66a15707a399d9d3c085a3b3
